name: 'Setup Rails Environment'
description: 'Sets up Ruby and installs dependencies with caching'
runs:
  using: "composite"
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version-file: .ruby-version
        bundler-cache: true
